### ISSUE TITLE
don't have primary CTA a PDF on /onboard/first primary CTA 

### ISSUE THREAD

**Issue by karamassie** [hackclub/site#1004]
Let's make the primary CTA to get a grant

lower on the page have a link especially for FIRST Team Leaders . Call the PDF a 'downloadable workshop to run in team meetings'

**Comment by maxwofford** [comment]
Let's def rename the "Download the PDF" link to something that makes more since.

This page is specifically for FIRST teams and will have a higher ratio of adults who are looking to run this as an activity, similar to how https://hackclub.com/hcb/first/ is for adult leaders. I think the PDF 'lesson plan' should be at the top as the primary CTA or secondary CTA. How about we drop the "learn PCB design" CTA and replace it with "get the grant"?

**Comment by karamassie** [comment]
yes! so the 2 buttons will be:

GET THE GRANT 
PCB WORKSHOPS FOR TEAMS 

?

**Comment by maxwofford** [comment]
Yeah, I'm a :+1: on this!

- "get the grant" links to the readme with steps to get the grant
- "pcb workshops for teams" links to the FIRST pdf.

**Comment by grymmy** [comment]
@maxwofford just wondering - was this done already?  or is this still planned?

**Comment by maxwofford** [comment]
Closing this as won't fix– this page isn't very trafficked and the intent of PDF is because it's mostly used by parents of FRC teams.
