### ISSUE TITLE
API: Games API Not Working

### ISSUE THREAD

**Issue by tobySolutions** [hackclub/site#966]
In the `games.js` file, I observed a very disturbing error, that prevented me from running the project locally and it was breaking the local version on my machine. Screenshots
<img width="1512" alt="Screenshot 2023-10-18 at 23 50 18" src="https://github.com/hackclub/site/assets/96334363/0cd42b9c-ad67-4bba-94e2-7e2efbd05b43">

<img width="1512" alt="Screenshot 2023-10-18 at 23 50 12" src="https://github.com/hackclub/site/assets/96334363/eaadb4df-c5c9-4368-9138-e25da991fb09">
 below:

**Comment by aramshiva** [comment]
@tobySolutions have you tried `yarn dev`? or something like that? I believe thats the intended way to run it locally.

**Comment by JosiasAurel** [comment]
Weird that you don't get the metadata.json from github. Perhaps you can try on another network (has happened to me a few times) 

There's a new gallery API in sprig. [sprig.hackclub.com/api/gallery](https://sprig.hackclub.com/api/gallery) that you can use to access games that is to be used instead of currently fetching the metadata.json from github. 

Please re-open if this does not work for you.
